# Generated by Django 3.1.4 on 2021-08-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210807_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
